#!/usr/bin/env python3
"""Regenerate emoji.txt from Unicode's emoji-test.txt.

    ./regen.py [path/to/emoji-test.txt] > emoji.txt

Without an argument the latest file is fetched from unicode.org. Only
fully-qualified sequences are kept. Skin-tone variants are folded into the
base emoji they modify rather than listed on their own, so the palette shows
each emoji once and the tone chosen by the user selects the variant.
Multi-person sequences with two different tones are dropped: they are far too
many to show, and a single tone setting cannot express them.

Output, one entry per line, tab separated:

    <group>\t<subgroup>\t<codepoints>\t<name>\t<tone variants>

where codepoints are hex separated by '-', and the tone variants are five
such sequences (light .. dark) separated by spaces, or empty.
"""

import re
import sys
import urllib.request

TONES = [
    "light skin tone",
    "medium-light skin tone",
    "medium skin tone",
    "medium-dark skin tone",
    "dark skin tone",
]

source = sys.argv[1] if len(sys.argv) > 1 else None
if source:
    text = open(source, encoding="utf-8").read()
else:
    with urllib.request.urlopen("https://unicode.org/Public/emoji/latest/emoji-test.txt") as r:
        text = r.read().decode("utf-8")

version = next((l.split(":", 1)[1].strip() for l in text.splitlines() if l.startswith("# Version")), "?")

entries = []  # (group, subgroup, codepoints, name)
group = subgroup = ""
for line in text.splitlines():
    if line.startswith("# group:"):
        group = line.split(":", 1)[1].strip()
    elif line.startswith("# subgroup:"):
        subgroup = line.split(":", 1)[1].strip()
    elif line and not line.startswith("#"):
        left, _, comment = line.partition("#")
        cps, _, status = left.partition(";")
        if status.strip() != "fully-qualified":
            continue
        # "# 😀 E1.0 grinning face"
        m = re.match(r"\s*\S+\s+E\d+\.\d+\s+(.*)", comment)
        name = m.group(1).strip()
        entries.append((group, subgroup, "-".join(cps.split()), name))

def base_name(name):
    """The name without its (single) skin-tone phrase, or None if it has two."""
    if len(name.split("skin tone")) - 1 != 1:
        return None
    # Longest phrase first: "medium-light skin tone" contains "light skin tone".
    tone = next(t for t in sorted(TONES, key=len, reverse=True) if t in name)
    index = TONES.index(tone)
    for sep in (": " + tone + ", ", ", " + tone, ": " + tone):
        if sep in name:
            stripped = name.replace(sep, ": " if sep.endswith(", ") else "", 1)
            return stripped, index
    return None

bases = {}
order = []
for group, subgroup, cps, name in entries:
    if group == "Component":
        continue
    if "skin tone" not in name:
        key = name
        bases[key] = [group, subgroup, cps, name, [""] * 5]
        order.append(key)

dropped = 0
for group, subgroup, cps, name in entries:
    if "skin tone" not in name or group == "Component":
        continue
    resolved = base_name(name)
    if resolved and resolved[0] in bases:
        bases[resolved[0]][4][resolved[1]] = cps
    else:
        dropped += 1

out = sys.stdout
out.write(f"# Generated by regen.py from Unicode emoji-test.txt, version {version}.\n")
out.write("# © Unicode, Inc. — https://www.unicode.org/terms_of_use.html\n")
out.write("# group\tsubgroup\tcodepoints\tname\ttone variants (light..dark)\n")
for key in order:
    group, subgroup, cps, name, tones = bases[key]
    tone_field = " ".join(tones) if any(tones) else ""
    out.write(f"{group}\t{subgroup}\t{cps}\t{name}\t{tone_field}\n")
sys.stderr.write(f"{len(order)} emoji, {dropped} multi-tone sequences dropped\n")
