[package]
name = "xdg-desktop-portal-otto"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Otto implementation of the org.freedesktop.portal interface"
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
async-io = "2"
anyhow.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
zbus = { workspace = true, features = ["async-io"] }

[lints]
workspace = true
